version: "3.7"

services:
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      ports:
          - 8081:80
      links:
          - mysql
      environment:
          - PMA_ARBITRARY=1
  mysql:
      image: mysql:8.0
      ports:
          - 3307:3306
      volumes:
          - mysql-data:/var/lib/mysql
      environment:
          MYSQL_ROOT_PASSWORD: 1
          MYSQL_DATABASE: laravel
  web:
    tty: true
    stdin_open: true
    command: bash
    build: ./docker
    links:
        - mysql
    ports:
        - 8088:8000
    environment:
        APP_DEBUG: 'true'
        XDEBUG_MODE: coverage
        PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/app/vendor/bin
    volumes:
        - .:/app:cached
        - ./docker-dev/web/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
        - ./docker/supervisor/:/etc/supervisor.d/
volumes:
    composer_caches:
    mysql-data:
